services:
  - type: web
    name: safeland
    runtime: python
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 backend.app:app
    envVars:
      - key: FLASK_DEBUG
        value: False
      - key: PYTHON_VERSION
        value: "3.11"
    buildCommand: |
      # Build frontend
      cd app && npm install && npm run build && cd ..
      # Install backend dependencies
      pip install -r backend/requirements.txt
    rootDir: .
